### PR TITLE
Switch printf library implementations

### PR DESCRIPTION
**Pull request by phillipjohnston**
Cannot merge yet - printf("string with no args") is not functional

### CODE REVIEW

**Comment by eyalroz** [comment]
Your last commit may _perhaps_ be obviated by `-fno-builtin-printf` . See discussion at eyalroz/printf#76 .

**Comment by phillipjohnston** [comment]
The problem here is that it's an arduino library, so I don't have a good way about enforcing build flags. For that approach (which I favor), I need EVERYONE to adjust their local rules for the AVR cores or whatever other architectures to apply that flag.

**Comment by eyalroz** [comment]
In that case - won't you also need to define a `putchar()`, avoiding replacements of `printf("%c", ch)` with `putchar(ch)` ?

**Comment by phillipjohnston** [comment]
Yes, certainly right.

**Comment by phillipjohnston** [comment]
Probably means I should just handle it via #27 (changing the macro approach)

**Comment by phillipjohnston** [comment]
Yeah, redefining puts works fine, but putchar just opens a new can of worms of unwanted compiler optimizations.

**Pull request merged**
